<main class="container">
    <h2 class="question"><?php echo $lang['contact_h2']; ?></h2>
    <div class="formulaires center">
        <h1><?php echo $lang['contact_h1']; ?></h1>
        <?php
        require '../BDD/connexion.php';
        require '../BDD/content.php';
        $erreur="";
        $succes= $lang['contact_p_envoie'];
        //Verification que les données soit saisies
        if((isset($_POST['submit'],$_POST['name'])) && empty($_POST['name'])) $erreur =  $lang['contact_p_name'];
        if((isset($_POST['submit'],$_POST['mail'])) && empty($_POST['mail']) && (filter_var($_POST['mail'], FILTER_VALIDATE_EMAIL))) $erreur = $lang['contact_p_mail'];
        if((isset($_POST['submit'],$_POST['themes'])) && (empty($_POST['themes']) || ($_POST['themes']==""))) $erreur = $lang['contact_p_theme'];
        if((isset($_POST['submit'],$_POST['message'])) && empty($_POST['message'])) $erreur = $lang['contact_p_message'];
        
        
        //Contrôle des formats des deux paramètres via les expressions régulières
        if(isset($_POST['submit'],$_POST['name'],$_POST['mail'],$_POST['themes'],$_POST['choose_job'],$_POST['message']) && $erreur=="")
        {
            //Initialisation de l'objet PDO et ouverture de la connexion pour appel à la base de données
            $db = getConnection();  
        
            //Tableau associatif pour requête d'insertion 
            $data = array(
                'nom' => $_POST['name'],
                'mail' => $_POST['mail'],
                'themes' => $_POST['themes'],
                'choose_job' => $_POST['choose_job'],
                'message' => $_POST['message']);
        
                // Appel de ma fonction de sauvegarde
                saveUser($db, $data);
                saveContent($db, $data);
                
                echo $succes;
        } 
        if($erreur!=""){
            echo $erreur;
        }
        ?>
        <form method="POST" action="contact.php">
        <!-- NOM/PRENOM -->
        <input type="text" name="name" placeholder="Your Name" />
        <!-- MAIL -->
        <input type="email" name="mail"  placeholder="Email Address"/>
        <select name="themes" id="themes" onchange=display()>
            <option value=""><?php echo $lang['contact_select_jobs1']; ?></option>
            <option id="jobs" value='jobs'>Jobs</option>
            <option value="information">Information</option>
            <option value="project"><?php echo $lang['contact_select_jobs2']; ?></option>
        </select>
        <!-- JOB -->
        <select class="hide" name="choose_job" id="choosejob" >
            <option value=""><?php echo $lang['contact_select_choosejobs1']; ?></option>
            <option value='electricien_chantier'><?php echo $lang['carriere_h3_1']; ?></option>
            <option value="manageur"><?php echo $lang['carriere_h3_2']; ?></option>
            <option value="ingenieur"><?php echo $lang['carriere_h3_3']; ?></option>
            <option value="electricien"><?php echo $lang['carriere_h3_4']; ?></option>
        </select>
        <!-- MESSAGE -->
        <textarea name="message" placeholder="Type your Message"></textarea>
        <!-- ENVOIE -->
        <input type="submit" name="submit" value="Envoyer">
        </form>
    </div>
    <div>
        <img class="photo_bureau" src="../images/bureaularge.jpg" alt="Bureau d'une entreprise" data-aos="fade-down" data-aos-duration="2000">
    </div>
</main>    