<main class="container">
    <section class="main">
        <div class="textmain">
            <h1>conet<span>C</span>om</h1>
            <p><?php echo $lang['acceuil_image_p']; ?></p>
        </div>
    </section>
    <article class="information center">
        <h2 data-aos="fade-down" data-aos-delay="350" data-aos-duration="1000"><?php echo $lang['acceuil_h2']; ?></h2>
        <p data-aos="fade-down" data-aos-delay="350" data-aos-duration="1000"><?php echo $lang['acceuil_p1']; ?></p>
        <p data-aos="fade-up" data-aos-delay="400" data-aos-duration="1000"><?php echo $lang['acceuil_p2']; ?></p>
        <a href="#" data-aos="fade-up" data-aos-delay="400" data-aos-duration="1000"><?php echo $lang['acceuil_a1']; ?></a>
    </article>
    <div data-aos="fade-down" data-aos-duration="2000">
        <img  class="photo_large" src="../images/lumiere_large.jpg" alt="lumiere bleu">
    </div>
    <div class="about center" data-aos="zoom-in-up" data-aos-duration="2000">
        <article>
            <img src="../images/fibre2.png" alt="Fibre">
            <h3><?php echo $lang['about_h3_1']; ?></h3>
            <div class="colored-line"></div>
            <p><?php echo $lang['about_p1']; ?></p>
            <a href="about.php"><?php echo $lang['about_a']; ?></a>
        </article>
        <article>
            <i class="far fa-lightbulb"></i>
            <h3><?php echo $lang['about_h3_2']; ?></h3>
            <div class="colored-line"></div>						
            <p><?php echo $lang['about_p2']; ?></p>
            <a href="about.php"><?php echo $lang['about_a']; ?></a>						
        </article>
        <article>
            <i class="fa fa-newspaper-o"></i>
            <h3><?php echo $lang['about_h3_3']; ?></h3>
            <div class="colored-line"></div>
            <p><?php echo $lang['about_p3']; ?></p>
            <a href="about.php"><?php echo $lang['about_a']; ?></a>						
        </article>
    </div>
    <div data-aos="fade-down" data-aos-duration="2000">
        <img class="photo_large" src="../images/association.jpg" alt="lumiere bleu">
    </div>
    <div class="adress center" data-aos="flip-up" data-aos-duration="2000">
        <div>
            <h4><?php echo $lang['about_siege_social']; ?> Basel</h4>
            <h4>conetCom AG</h4>
            <p>Güterstrasse 126</p>
            <p>CH-4053 Basel</p>
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
            <a href="tel:+41612703111">+41 61 270 31 11</a> 
        </div>
        <div>
            <h4>Filiale Le Lignon Geneve</h4>
            <h4>conetCom SA</h4>
            <p>Chemin de la Muraille 12</p>
            <p>CH-1219 Le Lignon</p>
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
            <a href="tel:+41223014866">+41 22 301 48 66</a> 
        </div>
        <div>
            <h4>Filiale Sion VS</h4>
            <h4>conetCom SA</h4>
            <p>Route de Vissigen 68</p>
            <p>CH-1950 Sion</p>
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
            <a href="tel:+41274558058">+41 27 455 80 58</a> 
        </div>
        <div>
            <h4>Filiale Dübendorf ZH</h4>
            <h4>conetCom ZH</h4>
            <p>Sonnentalstrasse 5</p>
            <p>CH-8600 Dübendorf</p>
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
            <a href="tel:+41274558058">+41 43 233 05 40</a> 
        </div>
    </div>
</main>
