<main class="container">
    <div class="main job"></div>
    <article class="information_job center" data-aos="fade-up" data-aos-delay="250" data-aos-duration="1000">
        <h2><?php echo $lang['information_h2']; ?></h2>
        <p><?php echo $lang['information_p1']; ?></p>
        <p><?php echo $lang['information_p2']; ?></p>
        <h4><?php echo $lang['information_h4']; ?></h4>
    </article>
    <div class="carriere center">
        <div data-aos="fade-down" data-aos-delay="250" data-aos-duration="1000">
            <i class="fas fa-bolt"></i>
            <a href="job1.php"><h3><?php echo $lang['carriere_h3_1']; ?></h3></a>
            <small>conetCom AG,CH-4053 Basel<a href="job1.php"><i class="fas fa-long-arrow-alt-right direction"></i></a></small>
        </div>
        <div data-aos="fade-up" data-aos-delay="300" data-aos-duration="1000">
            <i class="fas fa-wifi"></i>
            <a href="job2.php"><h3><?php echo $lang['carriere_h3_2']; ?></h3></a>
            <small>conetCom AG,CH-4053 Basel<a href="job2.php"><i class="fas fa-long-arrow-alt-right direction"></i></a></small>
        </div>
        <div data-aos="fade-down" data-aos-delay="350" data-aos-duration="1000">
            <i class="fas fa-pen"></i>
            <a href="job3.php"><h3><?php echo $lang['carriere_h3_3']; ?></h3></a>
            <small>conetCom SA,CH-1219 Le Lignon<a href="job3.php"><i class="fas fa-long-arrow-alt-right direction"></i></a></small>
        </div>
        <div data-aos="fade-up" data-aos-delay="400" data-aos-duration="1000">
            <i class="fas fa-laptop"></i>
            <a href="job4.php"><h3><?php echo $lang['carriere_h3_4']; ?></h3></a>
            <small>conetCom SA,CH-1950 Sion<a href="job4.php"><i class="fas fa-long-arrow-alt-right direction"></i></a></small>
        </div>
    </div>
    <div>
        <img class="photo_large" src="../images/christina.jpg" alt="Personne écrivant sur un clavier" data-aos="fade-down" data-aos-duration="2000">
    </div>
    <div class="adress center" data-aos="flip-up" data-aos-duration="2000">
        <div>
            <h4><?php echo $lang['about_siege_social']; ?> Basel</h4>
            <h4>conetCom AG</h4>
            <p>Güterstrasse 126</p>
            <p>CH-4053 Basel</p>
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
            <a href="tel:+41612703111">+41 61 270 31 11</a> 
        </div>
        <div>
            <h4>Filiale Le Lignon Geneve</h4>
            <h4>conetCom SA</h4>
            <p>Chemin de la Muraille 12</p>
            <p>CH-1219 Le Lignon</p>
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
            <a href="tel:+41223014866">+41 22 301 48 66</a> 
        </div>
        <div>
            <h4>Filiale Sion VS</h4>
            <h4>conetCom SA</h4>
            <p>Route de Vissigen 68</p>
            <p>CH-1950 Sion</p>
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
            <a href="tel:+41274558058">+41 27 455 80 58</a> 
        </div>
        <div>
            <h4>Filiale Dübendorf ZH</h4>
            <h4>conetCom ZH</h4>
            <p>Sonnentalstrasse 5</p>
            <p>CH-8600 Dübendorf</p>
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
            <a href="tel:+41274558058">+41 43 233 05 40</a> 
        </div>
    </div>
</main>    


        