<?php
include('../languages/fb.php');
?>
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0 user-scalable=no">
    <!-- STYLE -->
    <link rel="stylesheet" href="../CSS/style.css">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <!-- JS -->
    <script src="../JS/main.js" defer></script>
    <script src="../JS/maps.js" defer></script>
    <script src="../JS/formulaire.js" defer></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCncH65p90tDp4ICqq_4w18SKefgz8FhV0&callback=initMap" defer></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <!-- FONT AWESOME -->
    <script src="https://kit.fontawesome.com/3903820350.js" crossorigin="anonymous"></script>
    <!-- LOGO SITE -->
    <link rel="shortcut icon" type="image/ico" href="../images/logo_conet.ico"/>
    <!-- GOOGLE FONT-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&family=Ubuntu&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>conetCom - Competence for Network and Communication</title>
</head>
<body>
    <header class="header">
        <div id="menu-button" class="close"></div>
            <nav id="menu">    
                <a href="index"><?php echo $lang['one']; ?></a>
                <a href="about"><?php echo $lang['two']; ?></a>
                <a href="location"><?php echo $lang['three']; ?></a>
                <a href="job"><?php echo $lang['four']; ?></a>
                <a href="contact"><?php echo $lang['five']; ?></a>
            </nav>
        <div class="logo">
            <a href="index.php"><img src="../images/logo_ecriture.png" alt="Logo de l'entreprise Conectcom"></a>
        </div>
        <div class="trad">
            <?php 
            echo " <a href='".$_SERVER['SCRIPT_NAME']."?lang=fr'><img src='../images/france.png' alt='Drapeau francais'></a>";
            echo " <a href='".$_SERVER['SCRIPT_NAME']."?lang=de'><img src='../images/allemand.png' alt='Drapeau allemand'></a>";
            ?>
        </div>    
    </header>
    <main>
        <!-- Chargement du template (le fichier .phtml spécifique à la page) -->
        <?php require $template . '.phtml' ?>
    </main>

    <footer class="container">
        <div>
            <p>Copyright © 2021 conetCom® | <a href="#">by Axel</a></p>
        </div>
            <a href="#"><img class="reseaux" src="../images/instagram-brands.svg" alt="logo instagram"></a>
            <a href="#"><img class="reseaux" src="../images/twitter-brands.svg" alt="logo twitter"></a>
    </footer> 

<script>
    AOS.init();
</script>     
</body>