<main class="container">
    <div class="main location"></div>
    <article class="liste" data-aos="fade-down" data-aos-duration="2000">
        <h3><?php echo $lang['localisation_p']; ?></h3>
        <ul>
            <li><?php echo $lang['localisation_li1']; ?></li>
            <li><?php echo $lang['localisation_li2']; ?></li>
            <li><?php echo $lang['localisation_li3']; ?></li>
            <li><?php echo $lang['localisation_li4']; ?></li>
            <li><?php echo $lang['localisation_li5']; ?></li>
            <li><?php echo $lang['localisation_li6']; ?></li>
        </ul>
    </article>
    <h2 class="middle" data-aos="fade-down" data-aos-duration="2000"><?php echo $lang['localisation_h2']; ?></h2>
    <div id="map" data-aos="fade-down" data-aos-duration="2000"></div>
    <div class="adress center" data-aos="flip-up" data-aos-duration="2000">
        <div>
            <h4><?php echo $lang['about_siege_social']; ?> Basel</h4>
            <h4>conetCom AG</h4>
            <a href="https://goo.gl/maps/a9Yufqf8rhgdCexYA" target="_blank">Güterstrasse 126</a>
            <p>CH-4053 Basel</p>
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
            <a href="tel:+41612703111">+41 61 270 31 11</a> 
        </div>
        <div>
            <h4>Filiale Le Lignon Geneve</h4>
            <h4>conetCom SA</h4>
            <a href="https://goo.gl/maps/Ar8crhpAoXjVFRU46" target="_blank">Chemin de la Muraille 12</a>
            <p>CH-1219 Le Lignon</p>
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
            <a href="tel:+41223014866">+41 22 301 48 66</a> 
        </div>
        <div>
            <h4>Filiale Sion VS</h4>
            <h4>conetCom SA</h4>
            <a href="https://goo.gl/maps/kzYa4MKuBSEj9HyT8" target="_blank">Route de Vissigen 68</a>
            <p>CH-1950 Sion</p>
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
            <a href="tel:+41274558058">+41 27 455 80 58</a> 
        </div>
        <div>
            <h4>Filiale Dübendorf ZH</h4>
            <h4>conetCom ZH</h4>
            <a href="https://goo.gl/maps/SphgpsLSRyPpWhbFA" target="_blank">Sonnentalstrasse 5</a>
            <p>CH-8600 Dübendorf</p>
            <p><a href="mailto:info@conetCom.ch" target="_blank">info@conetCom.ch</a></p>
            <a href="tel:+41274558058">+41 43 233 05 40</a> 
        </div>
    </div>
</main>    